// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectApi.DataAccess;

namespace ProyectApi.DataAccess.Migrations
{
    [DbContext(typeof(ProyectDBContext))]
    partial class ProyectDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProyectApi.DataAccess.Contracts.Entities.EspecieEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ADNs")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isMutant")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Especies");
                });
#pragma warning restore 612, 618
        }
    }
}
